import { Outfit } from "next/font/google";
import "./globals.css";

const outfitsans = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "DeafNotes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${outfitsans.variable} antialiased`}>{children}</body>
    </html>
  );
}
